# Generated by Django 3.2.6 on 2021-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(default=4),
        ),
    ]
