# Generated by Django 3.2.6 on 2021-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_num',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
