# Generated by Django 3.2.6 on 2021-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
